name: Run API Tests

on:
  push:
    branches: ["main", "parallel_tests_api"]
  pull_request:
    branches: ["main", "parallel_tests_api"]

jobs:
  parallel-tests:
    name: Run parallel tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Rodar testes paralelos
        run: mvn clean verify
