name: Run API Tests with Both Jobs Always

on:
  push:
    branches: ["main", "parallel_tests_api"]
  pull_request:
    branches: ["main", "parallel_tests_api"]

jobs:
  run-on-main:
    name: Run tests on main branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Run tests on main
        run: mvn clean verify

  run-on-parallel:
    name: Run tests on parallel_tests_api branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Run parallel tests
        run: mvn clean verify
