name: Run API Tests

on:
  push:       # roda em todos os pushes em qualquer branch
  pull_request:  # roda em qualquer PR, qualquer branch de origem/destino

jobs:
  parallel-tests:
    name: Run parallel tests on any branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Rodar testes paralelos
        run: mvn clean verify
